# SPRING PROFILES
spring:
  #  profiles:
  #    active: dev

  # HTTP ENCODING
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
  server:
    port: 8888
    address: 127.0.0.1
    session-timeout: 60

#  # static
#  devtools:
#    livereload:
#      enabled: true

  # mysql
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/monitor?characterEncoding=utf-8&useUnicode=true&zeroDateTimeBehavior=convertToNull
    username: monitor
    password: monitor
    driverClassName: com.mysql.jdbc.Driver
    filters: stat,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    useGlobalDataSourceStat: true
    type: com.zaxxer.hikari.HikariDataSource # 其性能比常用的 c3p0、tomcat、bone、vibur 这些要高很多

monitor:
  base:
    path: http://127.0.0.1:8888/monitor/

  # user module
  user:
    init:
      name: admin,test
      admin:
        username: admin
        password: P@ssw0rd
        attrs: "{'nick': '超级管理员','email':'heyan_kafeibuku@sina.com','status':1,'type':1}"
      test:
        username: test
        password: P@ssw0rd
        attrs: "{'nick': '普通用户','email':'156286821@qq.com','status':1,'type':2}"

# logger
logging:
  level:
    com.monitor: DEBUG

# mybatis
mybatis:
  type-aliases-package: com.monitor.**.domain
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
